### ISSUE TITLE
Access key says it should be a secret, but listed as an input in setup-maven

### ISSUE THREAD

**Issue by pennstatephil** [gradle/develocity-actions#82]
https://github.com/gradle/develocity-actions/blob/fe2eaabfb21609092ba561f69af0c33452c28001/setup-maven/action.yml#L7
Not sure if the description is correct (should be a secret) or not, but if so, shouldn't it be under "secrets" and not "inputs" for setup-maven?

**Comment by jprinet** [comment]
There is no way to specify that an input is a secret according to the doc:
https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions

**Comment by pennstatephil** [comment]
My apologies, I was looking at workflows recently where [you can explicitly define `secrets`](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onworkflow_callsecrets) to use from the repo. I understand this isn't possible in actions, just workflows. Closing, and thanks for your response.
